version: '3.8'

services:
  datadog:
    image: datadog/agent:latest
    container_name: datadog
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_SITE=${DD_SITE}
      - DD_API_KEY=${DD_API_KEY}
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=1
    ports:
      - '8125:8125/udp'

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
